baseurl: /warc-specifications

markdown: kramdown

permalink: pretty

github_repository: https://github.com/iipc/warc-specifications
reference_branch: master

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

exclude:
- "*/Makefile"

gems:
  - jekyll-redirect-from

